# Generated by Django 3.1.7 on 2021-04-09 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='signs')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('recognition_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loss', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('recognition_time', models.FloatField(default=0)),
                ('sign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sign')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
