# Generated by Django 3.1.7 on 2021-05-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recognition_time',
        ),
    ]
