# Generated by Django 3.1.7 on 2021-05-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210512_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
