# Generated by Django 3.1.7 on 2021-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210512_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bug', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
