# Generated by Django 3.1.7 on 2021-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reportbug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbug',
            name='bug',
            field=models.ImageField(upload_to='signs'),
        ),
    ]
