# Generated by Django 3.1.7 on 2021-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210512_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbug',
            name='bug',
            field=models.ImageField(upload_to='report'),
        ),
    ]
