# Generated by Django 3.1.7 on 2021-05-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reportbug_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportbug',
            old_name='user_id',
            new_name='user',
        ),
    ]
