# Generated by Django 3.1.7 on 2021-05-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210518_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='avg',
            field=models.IntegerField(default=0),
        ),
    ]
